// Données de démo réalistes pour les dashboards et plannings

export const demoEmployees = [
  {
    id: 'E001',
    name: 'Léa Dubois',
    role: 'Serveuse',
    department: 'Salle',
    status: 'Actif',
    type: 'CDI',
    hours: 35,
    hoursThisWeek: 28,
    nextShift: 'Aujourd\'hui 18:00',
    performance: { covers: 45, revenue: 1890 },
    avatar: 'LD',
  },
  {
    id: 'E002',
    name: 'Julien Petit',
    role: 'Manager',
    department: 'Direction',
    status: 'En shift',
    type: 'CDI',
    hours: 39,
    hoursThisWeek: 32,
    nextShift: 'Maintenant',
    performance: { covers: 0, revenue: 0 },
    avatar: 'JP',
  },
  {
    id: 'E003',
    name: 'Chloé Martin',
    role: 'Barista',
    department: 'Bar',
    status: 'Actif',
    type: 'CDD',
    hours: 25,
    hoursThisWeek: 20,
    nextShift: 'Demain 17:00',
    performance: { covers: 38, revenue: 1520 },
    avatar: 'CM',
  },
  {
    id: 'E004',
    name: 'Marc Lefebvre',
    role: 'Cuisinier',
    department: 'Cuisine',
    status: 'Actif',
    type: 'CDI',
    hours: 35,
    hoursThisWeek: 30,
    nextShift: 'Aujourd\'hui 18:00',
    performance: { covers: 0, revenue: 0 },
    avatar: 'ML',
  },
  {
    id: 'E005',
    name: 'Thomas Bernard',
    role: 'Plongeur',
    department: 'Cuisine',
    status: 'Actif',
    type: 'CDI',
    hours: 35,
    hoursThisWeek: 25,
    nextShift: 'Demain 09:00',
    performance: { covers: 0, revenue: 0 },
    avatar: 'TB',
  },
  {
    id: 'E006',
    name: 'Sophie Moreau',
    role: 'Serveuse',
    department: 'Salle',
    status: 'En shift',
    type: 'CDI',
    hours: 35,
    hoursThisWeek: 28,
    nextShift: 'Maintenant',
    performance: { covers: 52, revenue: 2184 },
    avatar: 'SM',
  },
  {
    id: 'E007',
    name: 'Antoine Rousseau',
    role: 'Cuisinier',
    department: 'Cuisine',
    status: 'Actif',
    type: 'CDD',
    hours: 30,
    hoursThisWeek: 24,
    nextShift: 'Demain 09:00',
    performance: { covers: 0, revenue: 0 },
    avatar: 'AR',
  },
  {
    id: 'E008',
    name: 'Emma Durand',
    role: 'Serveuse',
    department: 'Salle',
    status: 'Disponible',
    type: 'Extra',
    hours: 0,
    hoursThisWeek: 12,
    nextShift: 'Vendredi 18:00',
    performance: { covers: 28, revenue: 1176 },
    avatar: 'ED',
  },
]

export const demoShifts = [
  {
    employee: 'Léa Dubois',
    role: 'Serveuse',
    monday: { start: '09:00', end: '17:00', type: 'work', covers: 45, cost: 120 },
    tuesday: { start: '09:00', end: '17:00', type: 'work', covers: 42, cost: 120 },
    wednesday: null,
    thursday: null,
    friday: { start: '18:00', end: '23:00', type: 'work', covers: 38, cost: 100 },
    saturday: { start: '10:00', end: '16:00', type: 'work', covers: 35, cost: 90 },
    sunday: null,
  },
  {
    employee: 'Julien Petit',
    role: 'Manager',
    monday: { start: '10:00', end: '18:00', type: 'admin', covers: 0, cost: 150 },
    tuesday: null,
    wednesday: { start: '10:00', end: '18:00', type: 'work', covers: 0, cost: 150 },
    thursday: { start: '10:00', end: '18:00', type: 'work', covers: 0, cost: 150 },
    friday: null,
    saturday: null,
    sunday: null,
  },
  {
    employee: 'Chloé Martin',
    role: 'Barista',
    monday: null,
    tuesday: null,
    wednesday: null,
    thursday: { start: '17:00', end: '01:00', type: 'work', covers: 28, cost: 110 },
    friday: { start: '17:00', end: '01:00', type: 'work', covers: 35, cost: 110 },
    saturday: { start: '17:00', end: '01:00', type: 'work', covers: 42, cost: 110 },
    sunday: null,
  },
  {
    employee: 'Marc Lefebvre',
    role: 'Cuisinier',
    monday: { start: '09:00', end: '15:00', type: 'kitchen', covers: 0, cost: 130 },
    tuesday: { start: '09:00', end: '15:00', type: 'kitchen', covers: 0, cost: 130 },
    wednesday: null,
    thursday: null,
    friday: { start: '18:00', end: '23:00', type: 'kitchen', covers: 0, cost: 140 },
    saturday: null,
    sunday: { start: '10:00', end: '15:00', type: 'kitchen', covers: 0, cost: 130 },
  },
  {
    employee: 'Sophie Moreau',
    role: 'Serveuse',
    monday: { start: '18:00', end: '23:00', type: 'work', covers: 52, cost: 100 },
    tuesday: { start: '18:00', end: '23:00', type: 'work', covers: 48, cost: 100 },
    wednesday: { start: '18:00', end: '23:00', type: 'work', covers: 55, cost: 100 },
    thursday: null,
    friday: { start: '18:00', end: '23:00', type: 'work', covers: 62, cost: 100 },
    saturday: { start: '18:00', end: '23:00', type: 'work', covers: 68, cost: 100 },
    sunday: null,
  },
  {
    employee: 'Thomas Bernard',
    role: 'Plongeur',
    monday: null,
    tuesday: { start: '09:00', end: '17:00', type: 'work', covers: 0, cost: 90 },
    wednesday: { start: '09:00', end: '17:00', type: 'work', covers: 0, cost: 90 },
    thursday: { start: '09:00', end: '17:00', type: 'work', covers: 0, cost: 90 },
    friday: null,
    saturday: { start: '10:00', end: '16:00', type: 'work', covers: 0, cost: 80 },
    sunday: null,
  },
  {
    employee: 'Antoine Rousseau',
    role: 'Cuisinier',
    monday: { start: '18:00', end: '23:00', type: 'kitchen', covers: 0, cost: 140 },
    tuesday: { start: '18:00', end: '23:00', type: 'kitchen', covers: 0, cost: 140 },
    wednesday: { start: '18:00', end: '23:00', type: 'kitchen', covers: 0, cost: 140 },
    thursday: null,
    friday: null,
    saturday: { start: '18:00', end: '23:00', type: 'kitchen', covers: 0, cost: 140 },
    sunday: null,
  },
  {
    employee: 'Emma Durand',
    role: 'Serveuse',
    monday: null,
    tuesday: null,
    wednesday: null,
    thursday: null,
    friday: { start: '18:00', end: '23:00', type: 'work', covers: 28, cost: 100 },
    saturday: null,
    sunday: null,
  },
]

export const demoDailyTotals = {
  monday: { hours: 32, covers: 97, cost: 730 },
  tuesday: { hours: 24, covers: 90, cost: 600 },
  wednesday: { hours: 16, covers: 55, cost: 380 },
  thursday: { hours: 16, covers: 28, cost: 380 },
  friday: { hours: 40, covers: 163, cost: 890 },
  saturday: { hours: 36, covers: 187, cost: 810 },
  sunday: { hours: 5, covers: 0, cost: 130 },
}

export const demoKPIs = {
  masseSalariale: { value: '24,500€', delta: '-2.4%', trend: 'down', sub: 'vs N-1' },
  productivite: { value: '84.20€', delta: '+5.1%', trend: 'up', sub: 'Objectif: 80€' },
  heures: { value: '1,240h', delta: '+0.8%', trend: 'neutral', sub: '98% Staffing' },
  conformite: { value: '98/100', delta: '+2pts', trend: 'up', sub: 'Aucune violation' },
  couverts: { value: '156', delta: '+12%', trend: 'up', sub: 'Objectif: 140', target: 140 },
  ca: { value: '4,200€', delta: '+8.5%', trend: 'up', sub: 'vs hier', predicted: 3900 },
  factures: { value: '98', delta: '+5', trend: 'up', sub: 'Panier: 42.86€', panierMoyen: '42.86€' },
  tauxOccupation: { value: '78%', delta: '+3%', trend: 'up', sub: 'Capacité max' },
}

